### ISSUE TITLE
Feature Request: Spawn a PTY shell on WT-EXIT

### ISSUE THREAD

**Issue by SkyperTHC** [sandialabs/wiretap#22]
A method to spawn a PTY shell (with password/secret) on the WT-EXIT:

```
nc -vn 172.16.0.1 31337
```

**Comment by luker983** [comment]
Can you provide more context for why you want this feature? To me it sounds out-of-scope for the goals of this project (network accessibility)

**Comment by SkyperTHC** [comment]
Gladly.

The WT gets deployed and then the host is moved to a different network, or behind a firewall, or the admin screws something up. The feature would allow a secondary access to the system in a reverse-connect fashion.

**Comment by luker983** [comment]
I have a few concerns about this:
1. Adding shell spawning could make Wiretap more likely to be flagged by AV
2. If access through Wiretap is still working but you've lost access to the host via some networking issue, you should be able to get local access to the machine through Wiretap already by adding the target IP to your routes and then connecting normally (via SSH/SMB/RDP/etc.). 

Right now I don't plan to implement this. Feel free to reopen if you feel strongly about it
