### ISSUE TITLE
Error after a successful DNS query terminates server process

### ISSUE THREAD

**Issue by S3mprGumb1** [sandialabs/wiretap#30]
I'm getting an error after DNS requests that causes the server process to panic and terminate. My current workaround is to wrap the server in a while loop, but that's not very elegant. 

Roughly the same stack trace when the server is on linux or windows:
wiretap[.exe] : panic: unknown network protocol number 0
wiretap/transport/udp.getDataFromPacket()
    wiretap/transport/udp/udp.go:128

**Comment by luker983** [comment]
Thanks for the report! UDP conversation resources weren't being cleaned up correctly. Should be fixed now.
