### ISSUE TITLE
UPnP 

### ISSUE THREAD

**Issue by DaniilSokolyuk** [sandialabs/wiretap#34]
Hello, I'm using this on a Windows server, I connect my XBOX to it via router with wireguard, i have a problem that some applications and voice chat don't work on xbox, i noticed in the router logs that xbox opens UPnP port, when I use [xray-core](https://github.com/XTLS/Xray-core) with a simple client server wireguard [configuration](https://g800.pages.dev/wireguard) everything works, BUT in the case of xray-core xbox doesn't open the UPnP port

**Comment by luker983** [comment]
Hey! As I understand it, uPnP allows your Xbox to tell your router to forward a port, but if Wiretap is sitting in front of the router then that port will still be inaccessible from the Internet. 

Without having more details about your configuration it's hard to say if this will work, but you might try manually forwarding all of the ports Microsoft recommends here: https://support.xbox.com/en-US/help/hardware-network/connect-network/network-ports-used-xbox-live from the client to the server using the `wiretap expose` command. 

Keep in mind that exposing services to the Internet can be dangerous so be careful
